# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: busybox:latest

stages:
  - build
  - test
  - deploy
  

build1:
  stage: build
  script:
    - echo "Do your build1 here"

build2:
  stage: build
  script:
    - echo "Do your buildl2 here
    
test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy_sandbox:
  stage: deploy
  script:
    - echo "Deploy to sandbox server"
  environment:
    name: sandbox
    url: https://staging.example.com
  when: manual

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
    - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://example.com
  when: manual
  only:
    - master
